djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from djcrm.settings import STATIC_ROOT, STATIC_URL
from leads.views import landing_page, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name = 'landing-page'),
    path('leads/', include('leads.urls', namespace="leads") ),
    path('agents/', include('agents.urls', namespace="agents") ),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (lead_create, 
    lead_create_view, lead_delete, lead_list, 
    lead_detail, lead_update, card_view, 
    loadlistView, LeadDetailView, lead_update_view, 
    lead_delete_view, AssignAgentView,
    categoryListView, CategoryDetailView,
    LeadCategoryUpdateView)


app_name = "leads"

urlpatterns = [
    path('', lead_list, name = 'lead-list'),
    path('card/', loadlistView.as_view(), name = 'lead-card-view'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', lead_update_view.as_view(), name='lead-update'),
    path('<int:pk>/delete/', lead_delete_view.as_view(), name = 'lead-delete'),
    path('create/', lead_create_view.as_view(), name='lead-create'),
    path('<int:pk>/assign/', AssignAgentView.as_view(), name='lead-assign'),
    path('<int:pk>/assign_category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('categories/', categoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),

]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import SET_NULL
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent",null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",related_name="leads", on_delete=SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.email

class Category(models.Model):
    name = models.CharField(max_length=30)
    # New, contacted, converted, unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


    def __str__(self):
        return self.name       

def post_user_created_signal(sender,instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms import fields
from django.http import request
from leads.models import Lead, Agent
from django.contrib.auth import get_user_model

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',

        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
        )
        field_classes = {'username' : UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation = request.user.userprofile)
        super(AssignAgentForm,self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )
        
        

leads/views.py
from django.core.mail import send_mail
from django.db.models.query import InstanceCheckMeta, QuerySet
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views import generic
from .models import Category, Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, User, LeadCategoryUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganisorAndLoginRequiredMixin


#CRUD - Create, Retrieve, Update, Delete + List 
class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = 'landing.html'

def landing_page(request):
    return render (request, "landing.html")

class loadlistView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_card_view.html"
    context_object_name = "leads"

    def get_queryset(self):
        user =self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        
        context = super(loadlistView, self).get_context_data(**kwargs)
        user =self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile, 
            agent__isnull=True)

            context.update({
                "unassigned_leads":queryset
            })
        return context

def card_view(request):
    leads = Lead.objects.all()
    context = {
       
        "leads" : leads
    }
    return render (request,"leads/lead_card_view.html", context)


def lead_list(request):
    leads = Lead.objects.all()
    context = {
       
        "leads" : leads
    }
    return render(request, "leads/leads_page.html", context)

def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead":lead
    }
    return render(request, "leads/lead_detail.html", context)

class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user =self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset


def lead_create(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        'form':form
    }
    return render(request,"leads/lead_create.html", context)


class lead_create_view(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        #  TODO send email
        send_mail(
            subject="New lead",
            message="New lead has been created on the CRM",
            from_email="happystudentmemories@gmail.com",
            recipient_list=["surendarmanoj85@gmail.com"],
        )
        return super(lead_create_view, self).form_valid(form)
    

def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
           form.save()
           return redirect("/leads")
    context = {
        'form':form,
        'lead': lead
    }
    return render(request, "leads/lead_update.html", context)

class lead_update_view(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_queryset(self):
        user =self.request.user
        return Lead.objects.filter(organisation=user.userprofile)
       

    def get_success_url(self):
        return reverse("leads:lead-list")

def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

class lead_delete_view(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"
    def get_queryset(self):
        user =self.request.user
        return Lead.objects.filter(organisation=user.userprofile)
    
    def get_success_url(self):
        return reverse("leads:lead-list")


class AssignAgentView(OrganisorAndLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request":self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class categoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"


    def get_context_data(self, **kwargs):
        context = super(categoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organisor:
            queryset=Lead.objects.filter(
                organisation = user.userprofile
            )
        else:
            queryset = Lead.objects.filter(
                organisation = user.agent.organisation
            )
        
        context.update({
            "unassigned_lead_count":queryset.filter(category__isnull=True).count()
            
        })
        return context

    def get_queryset(self):
        user =self.request.user

        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile, 
                
                )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation,
                )
            
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)

        # qs = Lead.objects.filter(category=self.get_object())
        leads = self.get_object().leads.all()
        
        context.update({
            "leads":leads
        })
        return context

    def get_queryset(self):
        user =self.request.user

        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile, 
                
                )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation,
                )
            
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)

        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs={"pk":self.get_object().id})





# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadForm()
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             lead.first_name = first_name
#             lead.last_name = last_name
#             lead.age = age
#             lead.save()
#             return redirect("/leads")
#     context = {
#         'form':form,
#         'lead': lead
#     }
#     return render(request, "leads/lead_update.html", context)


# def lead_create(request):
    # form = LeadModelForm()
    # if request.method == 'POST':
    #     form = LeadModelForm(request.POST)
    #     if form.is_valid():
    #         print(form.cleaned_data)
    #         first_name = form.cleaned_data['first_name']
    #         last_name = form.cleaned_data['last_name']
    #         age = form.cleaned_data['age']
    #         agent = Agent.objects.first()
    #         Lead.objects.create(
    #             first_name = first_name,
    #             last_name = last_name,
    #             age = age,
    #             agent = agent
    #         )
    #         print("Lead has been created")
    #         return redirect("/leads")
    # context = {
    #     'form':form
    # }
#     return render(request,"leads/lead_create.html", context)

leads/templates/leads/assign_agent.html
{% extends "base.html"%}
{% block title %}Assign Agent{% endblock title %}
{% block content %}
     <a href="{% url "leads:lead-list" %}">Back</a>
        <h1>Assign an agent to this lead</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Assign</button>
        </form>
        <script src="" async defer></script>
{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}


{% block title %}
Categories
{% endblock title %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
          </tr>
        </thead>
        <tbody>
         
          {% for lead in leads %}
          <tr>
            <td class="px-4 py-3">
            <a class="text-blue-500" href= "{% url 'leads:lead-detail' lead.pk %}">{{lead.first_name}}</a></td>
            <td class="px-4 py-3">{{lead.last_name}}</td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}


{% block title %}
Categories
{% endblock title %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the categories our leads are under</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-4 py-3">
            Unassigned
            </td>
            <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
          </tr>
          {% for category in category_list %}
          <tr>
            <td class="px-4 py-3">
            <a href="{% url 'leads:category-detail' category.pk %}">
            {{category.name}}
            </a>
            </td>
            <td class="px-4 py-3">category count</td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_card_view.html
{% extends "base.html" %}
{% block title %}Leads - Card View{% endblock title %}
{% block content %}
  <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-list" %}'">Back</button>
  <div  class ="p-4 mt-5 w-full"><h1 class="text-4xl text-gray-800">Leads</h1></div>
      <hr />

        <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
    
    {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
            <p class="leading-relaxed text-base">This is lead number {{ lead.id }}. This is about {{lead.first_name}} and is assigned to {{lead.agent}}</p>
            <a href = '{% url "leads:lead-detail" lead.pk %}' class="mt-3 text-indigo-500 inline-flex items-center">Details
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
     {% endfor %}
    </div>
  </div>
</section>


<section class="text-gray-600 body-font">
{% if unassigned_leads.exists %}
<div class ="p-4 mt-5 w-full">
    <h1 class="text-4xl text-gray-800">Unassigned Leads</h1>
</div>
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
    
    {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
            <p class="leading-relaxed text-base">This is lead number {{ lead.id }}. This is about {{lead.first_name}} and is assigned to {{lead.agent}}</p>
            <a href = '{% url "leads:lead-assign" lead.pk %}' class="mt-3 text-indigo-500 inline-flex items-center">Assign Agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
     {% endfor %}
     {% endif %}

    </div>
  </div>
</section>

    {% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% block title %}Update Lead category{% endblock title %}
{% block content%}
     <a href="{% url "leads:lead-list" %}">Back</a>
        <h1>Update the Status - {{lead.first_name}} {{lead.last_name}}</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
        </form>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html"%}
{% block title %}Create Lead{% endblock title %}
{% block content %}
     <a href="{% url "leads:lead-list" %}">Back</a>
        <h1>Create a new lead</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Add</button>
        </form>
        <script src="" async defer></script>
{% endblock content %}
   

leads/templates/leads/lead_delete.html
{% extends "base.html"%}
{% block title %}Delete View{% endblock title %}
{% block content %}
     <a href="{% url "leads:lead-list" %}">Back</a>
        <h1>Are you sure you want to delete {{lead.first_name}} {{lead.last_name}}</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Delete</button>
        </form>
        <script src="" async defer></script>
{% endblock content %}
   

leads/templates/leads/lead_detail.html
  {% extends "base.html" %}
  {% block title %}Detailed View{% endblock title %}
  {% block content %}
    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-list" %}'">Back</button>
    <hr />
    <h1>
    This is the detail of {{lead.first_name}} {{lead.last_name}}
    </h1>
    <table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Agent Assigned</th>
    <th>Category</th>
  </tr>
 
        <tr>
    <th>{{lead.first_name}} {{lead.last_name}}</th>
    <th>{{lead.age}}</th>
    <th>{{lead.agent}}</th>
    <th><button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-category-update" lead.pk %}'">Update Category</button></th>
  </tr>
      
  </table>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block title %}Update Lead{% endblock title %}
{% block content%}
     <a href="{% url "leads:lead-list" %}">Back</a>
        <h1>Update the lead - {{lead.first_name}} {{lead.last_name}}</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
        </form>
{% endblock content %}
        

leads/templates/leads/leads_page.html
{% extends "base.html" %}
{% block title %}Lead List{% endblock title %}
{% block content %}
      <div class="row">
        <div class="column">
        <h1>
        This is the list of all leads we have
        </h1></div>
        <div class="column">
        <div class="row">
        <div class="column">
        {% if request.user.is_organisor %}
        <button class="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-create" %}'">Create</button>
        {% endif %}
        </div>
        <div class="column">
        <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-card-view" %}'">Card View</button>
        </div>
      </div>
      </div>
      </div>
    <hr />
    <table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Agent Assigned</th>
     {% if request.user.is_organisor %}
    <th></th>
    {% endif %}

  </tr>
  {% for lead in leads %}
        <tr>
    <th><a href="{% url "leads:lead-detail" lead.pk %}"><u class="flex ml-auto text-blue">{{lead.first_name}} {{lead.last_name}}</u></a></th>
    <th>{{lead.age}}</th>
    <th>{{lead.agent}}</th>
   {% if request.user.is_organisor %}
    <th><div class="row">
    <div class="column"> <button class="flex ml-auto text-black bg-yellow-300 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-update" lead.pk %}'">Update</button></div>
    <div class="column"><button class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "leads:lead-delete" lead.pk %}'">Delete</button></div>
    
    </div></th>
    {% endif %}
  </tr>
        {% endfor %}
  </table>
    {% endblock content %}