agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView, AgentDetailView,AgentUpdateView, AgentDeleteView

app_name = 'agents'


urlpatterns = [
    path('',AgentListView.as_view(), name='agent-list'),
    path('create/',AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from djcrm.settings import STATIC_ROOT, STATIC_URL
from leads.views import landing_page, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name = 'landing-page'),
    path('leads/', include('leads.urls', namespace="leads") ),
    path('agents/', include('agents.urls', namespace="agents") ),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name'
        )

agents/views.py
import random

from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin


class AgentListView(OrganisorAndLoginRequiredMixin,generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = organisation)

class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse ("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0,1000000)}")
        user.save()
        Agent.objects.create(
            user = user,
            organisation = self.request.user.userprofile
        )
        send_mail(
            subject="You are invited",
            message="You have been added as an agent to the CRM.",
            from_email = "happystudentmemories@gmail.com",
            recipient_list = [user.email]
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)

class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    queryset = Agent.objects.all()
    form_class = AgentModelForm
    def get_success_url(self):
        return reverse ('agents:agent-list')

class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    contect_object_name = "agent"

    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)

    def get_success_url(self):
        return reverse ('agents:agent-list')

agents/templates/agents/agent_create.html
{% extends "base.html"%}
{% block title %}Create Agent{% endblock title %}
{% block content %}
     <a href="{% url "agents:agent-list" %}">Back</a>
        <h1>Create a new agent</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Add</button>
        </form>
        <script src="" async defer></script>
{% endblock content %}
   

agents/templates/agents/agent_delete.html
{% extends "base.html"%}
{% block title %}Delete View{% endblock title %}
{% block content %}
     <a href="{% url "agents:agent-list" %}">Back</a>
        <h1>Are you sure you want to delete {{agent.user.username}}</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Delete</button>
        </form>
        <script src="" async defer></script>
{% endblock content %}

agents/templates/agents/agent_detail.html
  {% extends "base.html" %}
  {% block title %}Detailed View{% endblock title %}
  {% block content %}
    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "agents:agent-list" %}'">Back</button>
    <hr />
    <h1>
    This is the detail of {{agent.user.username}}
    </h1>
    <table>
  <tr>
    <th>Name</th>
    
  </tr>
 
        <tr>
    <th>{{ agent.user.username }}</th>
    
  </tr>
      
  </table>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block title %}
Agents
{% endblock title %}

{% block content %}
    <h1>Agents</h1>
  <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" onclick="window.location.href='{% url "agents:agent-create" %}'">Create</button>
      <hr />

        <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="flex flex-wrap -m-4">
    {% for agent in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
            <p class="leading-relaxed text-base">This is lead number {{ agent.user.username }}. This is about {{ agent.user.username }} and is assigned to {{agent.user.username}}</p>
            <a href = "{% url 'agents:agent-detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Details
            <a href = "{% url 'agents:agent-update' agent.pk %}" class="mt-3 m-4 text-indigo-500 inline-flex items-center">Update
            <a href = "{% url 'agents:agent-delete' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Delete
              
            </a>
          </div>
        </div>
      </div>
     {% endfor %}
    </div>
  </div>
</section>

{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% block title %}Update Agent Detail{% endblock title %}
{% block content%}
     <a href="{% url "agents:agent-list" %}">Back</a>
        <h1>Update the lead - {{agent.user.username}}</h1>
       
        <hr />
        <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
        </form>
{% endblock content %}