agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView, AgentDetailView,AgentUpdateView, AgentDeleteView

app_name = 'agents'


urlpatterns = [
    path('',AgentListView.as_view(), name='agent-list'),
    path('create/',AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from djcrm.settings import STATIC_ROOT, STATIC_URL
from leads.views import landing_page, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name = 'landing-page'),
    path('leads/', include('leads.urls', namespace="leads") ),
    path('agents/', include('agents.urls', namespace="agents") ),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (lead_create, 
    lead_create_view, lead_delete, lead_list, 
    lead_detail, lead_update, card_view, 
    loadlistView, LeadDetailView, lead_update_view, 
    lead_delete_view, AssignAgentView,
    categoryListView, CategoryDetailView,
    LeadCategoryUpdateView)


app_name = "leads"

urlpatterns = [
    path('', lead_list, name = 'lead-list'),
    path('card/', loadlistView.as_view(), name = 'lead-card-view'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', lead_update_view.as_view(), name='lead-update'),
    path('<int:pk>/delete/', lead_delete_view.as_view(), name = 'lead-delete'),
    path('create/', lead_create_view.as_view(), name='lead-create'),
    path('<int:pk>/assign/', AssignAgentView.as_view(), name='lead-assign'),
    path('<int:pk>/assign_category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('categories/', categoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
     <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href = "{% static 'css/styles.css' %}" rel = "stylesheet" />
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <style>
        .lead {
            padding-top:10px;
            padding-bottom:10px;
            padding-left:6px;
            paddin-right:6px;
            margin-top:10px;
            background-color:#f6f6f6;
            width:100%
        }
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

* {
  box-sizing: border-box;
}

td, th {
  border: 1px solid #000000;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.column {
  float: left;
  width: 50%;
  padding: 10px;
  border : 2px;
  
}

.row:after {
  content: "";
  display: table;
  clear: both;
}
        </style>
    </head>
    <body>
    {% include 'navbar.html'%}
    {% block content %}
    {% endblock content %}
    {% include "scripts.html" %}
    </body>
</html>

templates/landing.html
{% extends "base.html" %}

{% block content%}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to Leads module
        <br class="hidden lg:inline-block">of our CRM
      </h1>
      <p class="mb-8 leading-relaxed">This is a CRM built in Django</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    </div>
  </div>
</section>
{% endblock content%}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Happy Students</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
    {% if request.user.is_authenticated %}
    Hello {{ request.user.username}}, Welcome.
    <a href="{% url 'leads:lead-list' %}" class=" ml-3 mr-5 hover:text-gray-900">Leads</a>
     <a href="{% url 'leads:category-list' %}" class=" ml-3 mr-5 hover:text-gray-900">Categories</a>
    {% if request.user.is_organisor %}
    <a href="{% url 'agents:agent-list' %}" class=" ml-3 mr-5 hover:text-gray-900">Agents</a>
   
    {% endif %}
     <a href = "{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
    </a>
    {% else %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
    </nav>
    <a href = "{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}


<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Second Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Welcome {{ name }}, You are {{age}} years old</h1>
        <ul>
        {% for lead in leads%}
        <li>{{lead}}</li>
        {%endfor%}
        </ul>
        <script src="" async defer></script>
    </body>
</html>